-- Character catalog seed (exported from the live project 2026-10-03).
-- Model/thumbnail URLs point at the live project's public character-assets
-- bucket; after copying the bucket into another project, rewrite the host.

INSERT INTO public.characters (id, name, description, ability_id, currency, price_coins, price_cents, rarity, model_url, sort_order, is_active, created_at, thumbnail_url, model_scale, model_offset_y) VALUES ('rookie', 'Rookie', 'Rookie Runner — eager, fresh, and ready to chase a high score.', NULL, 'coins', 2000, 0, 'common', 'https://aralsgqeqyqufojrzcaj.supabase.co/storage/v1/object/public/character-assets/characters/rookie/model.glb', 1, true, '2026-06-28 17:11:24.655512+00', 'https://aralsgqeqyqufojrzcaj.supabase.co/storage/v1/object/public/character-assets/characters/rookie/thumb.webp', 1.0, 0);
INSERT INTO public.characters (id, name, description, ability_id, currency, price_coins, price_cents, rarity, model_url, sort_order, is_active, created_at, thumbnail_url, model_scale, model_offset_y) VALUES ('runner', 'Runner', 'The original. Reliable and ready to roll.', NULL, 'free', 0, 0, 'common', '/models/player.glb', 0, true, '2026-06-27 14:56:03.863731+00', NULL, 1, 0);
INSERT INTO public.characters (id, name, description, ability_id, currency, price_coins, price_cents, rarity, model_url, sort_order, is_active, created_at, thumbnail_url, model_scale, model_offset_y) VALUES ('magno', 'Magno', 'Magnetic powerhouse — built to pull coins and leave records behind.', NULL, 'coins', 7500, 0, 'rare', 'https://aralsgqeqyqufojrzcaj.supabase.co/storage/v1/object/public/character-assets/characters/magno/model.glb', 3, true, '2026-06-29 06:27:30.500336+00', 'https://aralsgqeqyqufojrzcaj.supabase.co/storage/v1/object/public/character-assets/characters/magno/thumb.webp', 1.0, 0);
INSERT INTO public.characters (id, name, description, ability_id, currency, price_coins, price_cents, rarity, model_url, sort_order, is_active, created_at, thumbnail_url, model_scale, model_offset_y) VALUES ('cyborg', 'Cyborg', 'Chrome-plated and circuit-fast — a machine built to leave records in the dust.', NULL, 'coins', 20000, 0, 'premium', 'https://aralsgqeqyqufojrzcaj.supabase.co/storage/v1/object/public/character-assets/characters/cyborg/model.glb', 5, true, '2026-06-29 10:21:19.52671+00', 'https://aralsgqeqyqufojrzcaj.supabase.co/storage/v1/object/public/character-assets/characters/cyborg/thumb.webp', 1.0, 0);
INSERT INTO public.characters (id, name, description, ability_id, currency, price_coins, price_cents, rarity, model_url, sort_order, is_active, created_at, thumbnail_url, model_scale, model_offset_y) VALUES ('inferno', 'Inferno', 'Forged in fire and clad in molten armor — every stride leaves the track scorched.', NULL, 'coins', 50000, 0, 'premium', 'https://aralsgqeqyqufojrzcaj.supabase.co/storage/v1/object/public/character-assets/characters/inferno/model.glb', 6, true, '2026-06-29 10:28:09.421307+00', 'https://aralsgqeqyqufojrzcaj.supabase.co/storage/v1/object/public/character-assets/characters/inferno/thumb.webp', 1.0, 0);
INSERT INTO public.characters (id, name, description, ability_id, currency, price_coins, price_cents, rarity, model_url, sort_order, is_active, created_at, thumbnail_url, model_scale, model_offset_y) VALUES ('ninja', 'Ninja', 'Silent, swift, and deadly precise — strikes through the run unseen.', NULL, 'coins', 15000, 0, 'rare', 'https://aralsgqeqyqufojrzcaj.supabase.co/storage/v1/object/public/character-assets/characters/ninja/model.glb', 4, true, '2026-06-29 06:39:04.99004+00', 'https://aralsgqeqyqufojrzcaj.supabase.co/storage/v1/object/public/character-assets/characters/ninja/thumb.webp', 1.0, 0);
INSERT INTO public.characters (id, name, description, ability_id, currency, price_coins, price_cents, rarity, model_url, sort_order, is_active, created_at, thumbnail_url, model_scale, model_offset_y) VALUES ('techy', 'Techy', 'Runner from the future, ready to change the future of running while beating your high score.', NULL, 'coins', 5000, 0, 'common', 'https://aralsgqeqyqufojrzcaj.supabase.co/storage/v1/object/public/character-assets/characters/techy/model-v1.glb', 2, true, '2026-06-29 06:16:14.416125+00', 'https://aralsgqeqyqufojrzcaj.supabase.co/storage/v1/object/public/character-assets/characters/techy/thumb-v1.webp', 1.0, 0);
